spring:
  config:
    import: optional:configserver:http://config-service:8888
  elasticsearch:
    uris: http://${ES_HOST}:9200
    connection-timeout: 1s
    socket-timeout: 3s
  cloud:
    config:
      fail-fast: true

apigateway:
  host: http://apigateway-service:8000

shop-service:
  url: http://shop-service:8085
