version: "3"

services:
  database:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: node5
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: my_routine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # Healthcheck 추가
      test: ["CMD-SHELL", "pg_isready -U node5 -d my_routine"]
      interval: 5s
      timeout: 5s
      retries: 5

  config-service:
    image: node5dev/config:latest
    ports:
      - "8888:8888"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - /home/ubuntu/config:/app/config
    healthcheck: # Healthcheck 추가
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  discovery-service:
    image: node5dev/discovery:latest
    ports:
      - "8761:8761"
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck: # Healthcheck 추가
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  billing-service:
    image: node5dev/billing-service:latest
    depends_on:
      discovery-service:
        condition: service_healthy
    env_file:
      - .env.billing

  catalog-service:
    image: node5dev/catalog-service:latest
    depends_on:
      discovery-service:
        condition: service_healthy
    env_file:
      - .env.catalog

  member-service:
    image: node5dev/member-service:latest
    depends_on:
      discovery-service:
        condition: service_healthy
    env_file:
      - .env.member

  order-service:
    image: node5dev/order-service:latest
    depends_on:
      discovery-service:
        condition: service_healthy
    env_file:
      - .env.order

  settlement-service:
    image: node5dev/settlement-service:latest
    depends_on:
      discovery-service:
        condition: service_healthy
    env_file:
      - .env.settlement

  shop-service:
    image: node5dev/shop-service:latest
    depends_on:
      discovery-service:
        condition: service_healthy
    env_file:
      - .env.shop

  subscription-service:
    image: node5dev/subscription-service:latest
    depends_on:
      discovery-service:
        condition: service_healthy
    env_file:
      - .env.subscription

  apigateway-service:
    image: node5dev/apigateway:latest
    ports:
      - "8000:8000"
    depends_on:
      discovery-service:
        condition: service_healthy

volumes:
  postgres_data: