services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

  database:
    image: pgvector/pgvector:pg17 # pgvector Extension이 설치된 postgresql 17버전
    restart: unless-stopped
    environment:
      POSTGRES_USER: node5
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: my_routine
      LANG: ko_KR.utf8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      bash -c "apt-get update && apt-get install -y locales 
      && sed -i 's/# ko_KR.UTF-8 UTF-8/ko_KR.UTF-8 UTF-8/' /etc/locale.gen 
      && locale-gen ko_KR.UTF-8 
      && exec docker-entrypoint.sh postgres"
    healthcheck: # Healthcheck 추가
      test: ["CMD-SHELL", "pg_isready -U node5 -d my_routine"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    restart: unless-stopped

    ports:
      - "9092:9092"
      - "9093:9093"

    environment:
      # === KRaft 기본 ===
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # === Listener ===
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      # === Controller ===
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # === Internal ===
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # === Cluster ===
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # === Heap ===
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m"

    volumes:
      - ./data/kafka:/var/lib/kafka/data

    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 20s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    restart: unless-stopped
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: node5
      RABBITMQ_DEFAULT_PASS: 1234

volumes:
  postgres_data:
  redis_data:
  es_data:
  npm_data:
  npm_letsencrypt:
