rootProject.name = 'my-routine'

include(
        'common',
        'apigateway',
        'batch-service',
        'config',
        'discovery',
        'catalog-service',
        'member-service',
        'order-service',
        'payment-service',
        'support-service',
        'wallet-service'
)
