spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        default-encoding: UTF-8
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

api:
  v1: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8081

token:
  secret: ${TOKEN_SECRET}
  expiration:
    access: 3600000
    refresh: 604800000

kakao:
  api:
    key: ${KAKAO_API_KEY}
  redirect:
    url: ${KAKAO_REDIRECT_URL}
