spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: support
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        default-encoding: UTF-8
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      delivery-mode: persistent
    listener:
      simple:
        default-requeue-rejected: false

api:
  v1: /api/v1

server:
  port: 8087
