spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        default-encoding: UTF-8
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      delivery-mode: persistent
    listener:
      simple:
        default-requeue-rejected: false

server:
  port: 8087
