spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jackson:
    time-zone: Asia/Seoul
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: support
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  batch:
    jdbc:
      initialize-schema: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        default-encoding: UTF-8
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      delivery-mode: persistent
    listener:
      simple:
        default-requeue-rejected: false
  kafka:
    # 1. 공통 설정: 카프카 클러스터 주소
    bootstrap-servers: ${KAFKA_HOST}:9092
    listener:
      ack-mode: manual

    # 2. Producer 설정 (메시지를 보내는 서비스: 예 - Order, Payment)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # 3. Consumer 설정 (메시지를 받는 서비스: 예 - Notification, Settlement)
    consumer:
      group-id: support-service # 서비스별 그룹 아이디
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest # 처음부터 읽을지(earliest) 마지막부터 읽을지(latest)
      enable-auto-commit: false # 오프셋 자동 커밋 여부
      properties:
        spring.json.trusted.packages: "com.node5.common.event"
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4.1-nano
          max-completion-tokens: 512
          temperature: 1.0
      embedding:
        options:
          model: text-embedding-3-small
kafka:
  topics:
    review-created: support-service.review-created.v1
    product-discontinued: catalog-service.product-discontinued.v1
    product-embedding: ai-service.product-embedding.v1
    order-status-changed: order-service.order-status-changed.v1
    subscription-status-changed: subscription-service.subscription-status-changed.v1
api:
  v1: /api/v1

server:
  port: 8087
