spring:
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/catalog-service/**
              filters:
                - RewritePath=/catalog-service/(?<segment>.*), /$\{segment}
            - id: member-service
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/member-service/api/v1/**, /member-service/v3/api-docs/**
              filters:
                - RewritePath=/member-service/(?<segment>.*), /$\{segment}
            - id: subscription-service
              uri: lb://SUBSCRIPTION-SERVICE
              predicates:
                - Path=/subscription-service/**
              filters:
                - RewritePath=/subscription-service/(?<segment>.*), /$\{segment}
            - id: settlement-service
              uri: lb://SETTLEMENT-SERVICE
              predicates:
                - Path=/settlement-service/**
              filters:
                - RewritePath=/settlement-service/(?<segment>.*), /$\{segment}
                - RewritePath=/subscription-service/(?<segment>.*), /$\{segment}
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-service/**
              filters:
                - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - id: support-service
              uri: lb://SUPPORT-SERVICE
              predicates:
                - Path=/support-service/**
              filters:
                - RewritePath=/support-service/(?<segment>.*), /$\{segment}
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment-service/**
              filters:
                - RewritePath=/payment-service/(?<segment>.*), /$\{segment}
            - id: wallet-service
              uri: lb://WALLET-SERVICE
              predicates:
                - Path=/wallet-service/**
              filters:
                - RewritePath=/wallet-service/(?<segment>.*), /$\{segment}
            - id: batch-service
              uri: lb://BATCH-SERVICE
              predicates:
                - Path=/batch-service/**
              filters:
                - RewritePath=/batch-service/(?<segment>.*), /$\{segment}
          default-filters:
            - name: GlobalFilter
              args:
                preLogger: true
                postLogger: true
            - name: AuthenticationFilter
            - name: AuthorizationFilter
          discovery:
            locator:
              enabled: true


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info
    endpoint:
      health:
        probes:
          enabled: true

info:
  app:
    name: Spring Cloud Gateway
    description: API 라우팅 및 보안, 모니터링/메트릭 등의 기능을 간단하고 효과적인 방법으로 제공
  swagger-ui: http://localhost:8000/webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config
