apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: config
          image: node5dev/config:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 60
            failureThreshold: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: config-repo
              mountPath: /app/config/config
      volumes:
        - name: config-repo
          configMap:
            name: config-repo
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config
spec:
  type: ClusterIP
  selector:
    app: config
  ports:
    - name: http
      port: 8888
      targetPort: 8888
