apiVersion: v1
kind: ConfigMap
metadata:
  name: config-repo
data:
  application.yml: |
    token:
      secret: bqE8cz8S6bV4GzD2A1g7o1I2N7q9p+vTWlM3lBaEo+3gF5h4qXvBRvUj2bS7wQ0RzF1YkPb3pH8xq9kJz4ySXQ==
    eureka:
      instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        preferIpAddress: true
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://admin:admin@discovery-service:8761/eureka
    apigateway:
      host: http://apigateway-service:8000
    management:
      endpoints:
        web:
          exposure:
            include: health, info
      endpoint:
        health:
          probes:
            enabled: true
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 30s
  billing-service.yaml: |
    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        driver-class-name: org.postgresql.Driver
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      jackson:
        time-zone: Asia/Seoul
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: true
        properties:
          hibernate:
            default_schema: billing
            format_sql: true
            jdbc:
              time_zone: Asia/Seoul
      batch:
        jdbc:
          initialize-schema: never
      kafka:
        bootstrap-servers: ${KAFKA_HOST}:9092
        listener:
          ack-mode: manual
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
          group-id: billing-service
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          auto-offset-reset: latest
          enable-auto-commit: false
          properties:
            spring.json.trusted.packages: "com.node5.common.event"
    api:
      v1: /api/v1
    kafka:
      topics:
        wallet-deleted: billing-service.wallet-deleted.v1
        member-deleted: member-service.member-deleted.v1
    payment:
      toss:
        secret-key: ${TOSS_SECRET_KEY}
        success-url: ${TOSS_SUCCESS_URL}
        fail-url: ${TOSS_FAIL_URL}
  catalog-service.yaml: |
    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        driver-class-name: org.postgresql.Driver
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      jackson:
        time-zone: Asia/Seoul
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: true
        properties:
          hibernate:
            default_schema: catalog
            format_sql: true
            jdbc:
              time_zone: Asia/Seoul
      kafka:
        bootstrap-servers: ${KAFKA_HOST}:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    api:
      v1: /api/v1
    app:
      kafka:
        topics:
          member-deleted: member-service.member-deleted.v1
          product-index: catalog-service.product-index.v1
          product-embedding: catalog-service.product-embedding.v1
          product-discontinued: catalog-service.product-discontinued.v1
      s3:
        bucket: ${S3_BUCKET_NAME}
        region: ${AWS_REGION:ap-northeast-2}
        presigned-url-expiration-seconds: ${S3_PRESIGNED_EXPIRE:600}
  member-service.yaml: |
    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        driver-class-name: org.postgresql.Driver
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      jackson:
        time-zone: Asia/Seoul
      sql:
        init:
          mode: always
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: true
        properties:
          hibernate:
            default_schema: member
            format_sql: true
            jdbc:
              time_zone: Asia/Seoul
      mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
          mail:
            default-encoding: UTF-8
            smtp:
              auth: true
              starttls:
                enable: true
      data:
        redis:
          host: ${REDIS_HOST}
          port: 6379
      kafka:
        bootstrap-servers: ${KAFKA_HOST}:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
          group-id: member-service
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          auto-offset-reset: latest
          enable-auto-commit: false
          properties:
            spring.json.trusted.packages: "com.node5.common.event"
    api:
      v1: /api/v1
    management:
      endpoints:
        web:
          exposure:
            include: health
    server:
      port: 8081
    token:
      expiration:
        access: 3600000
        refresh: 604800000
    kakao:
      api:
        key: ${KAKAO_API_KEY}
    google:
      client:
        id: ${GOOGLE_CLIENT_ID}
        secret: ${GOOGLE_CLIENT_SECRET}
    naver:
      client:
        id: ${NAVER_CLIENT_ID}
        secret: ${NAVER_CLIENT_SECRET}
    kafka:
      topics:
        shop-deleted: member-service.shop-deleted.v1
        member-deleted: member-service.member-deleted.v1
  order-service.yaml: |
    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        driver-class-name: org.postgresql.Driver
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      jackson:
        time-zone: Asia/Seoul
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            jdbc:
              time_zone: Asia/Seoul
      sql:
        init:
          mode: always
    api:
      v1: /api/v1
    management:
      endpoints:
        web:
          exposure:
            include: health
  settlement-service.yaml: |
    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        driver-class-name: org.postgresql.Driver
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      jackson:
        time-zone: Asia/Seoul
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: true
        properties:
          hibernate:
            default_schema: settlement
            format_sql: true
            jdbc:
              time_zone: Asia/Seoul
      batch:
        jdbc:
          initialize-schema: always
          schema: public
        job:
          names: '*'
      task:
        scheduling:
          cron:
            settlement: ${SETTLEMENT_SCHEDULING_CRON}
    management:
      endpoints:
        web:
          exposure:
            include: health
    api:
      v1: /api/v1
  subscription-service.yml: |
    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        driver-class-name: org.postgresql.Driver
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      jackson:
        time-zone: Asia/Seoul
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: true
        properties:
          hibernate:
            default_schema: subscription
            format_sql: true
            jdbc:
              time_zone: Asia/Seoul
      kafka:
        bootstrap-servers: ${KAFKA_HOST}:9092
        listener:
          ack-mode: manual
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
          group-id: subscription-service
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          auto-offset-reset: latest
          enable-auto-commit: false
          properties:
            spring.json.trusted.packages: "com.node5.common.event"
      task:
        scheduling:
          cron:
            subscription-order: ${SUBSCRIPTION_ORDER_CRON}
    api:
      v1: /api/v1
    kafka:
      topics:
        member-deleted: member-service.member-deleted.v1
        shop-deleted: shop-service.shop-deleted.v1
  support-service.yaml: |
    spring:
      elasticsearch:
        uris: http://${ES_HOST}:9200
        connection-timeout: 1s
        socket-timeout: 3s
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        driver-class-name: org.postgresql.Driver
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      jackson:
        time-zone: Asia/Seoul
      sql:
        init:
          mode: always
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: true
        properties:
          hibernate:
            default_schema: support
            format_sql: true
            jdbc:
              time_zone: Asia/Seoul
      batch:
        jdbc:
          initialize-schema: never
      mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
          mail:
            default-encoding: UTF-8
            smtp:
              auth: true
              starttls:
                enable: true
      rabbitmq:
        host: ${RABBITMQ_HOST}
        port: 5672
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}
        template:
          delivery-mode: persistent
        listener:
          simple:
            default-requeue-rejected: false
      kafka:
        bootstrap-servers: ${KAFKA_HOST}:9092
        listener:
          ack-mode: manual
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
          group-id: support-service
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          auto-offset-reset: latest
          enable-auto-commit: false
          properties:
            spring.json.trusted.packages: "com.node5.common.event"
      ai:
        openai:
          api-key: ${OPEN_AI_API_KEY}
          base-url: https://api.openai.com
          chat:
            options:
              model: gpt-4.1-nano
              max-completion-tokens: 512
              temperature: 1.0
          embedding:
            options:
              model: text-embedding-3-small
    kafka:
      topics:
        review-created: support-service.review-created.v1
        product-discontinued: catalog-service.product-discontinued.v1
        product-embedding: catalog-service.product-embedding.v1
        product-index: catalog-service.product-index.v1
        order-status-changed: order-service.order-status-changed.v1
        subscription-status-changed: subscription-service.subscription-status-changed.v1
    api:
      v1: /api/v1
    app:
      search:
        index:
          product: products
    server:
      port: 8087
