apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - services/apigateway.yaml
  - services/batch-service.yaml
  - services/catalog-service.yaml
  - services/discovery.yaml
  - services/member-service.yaml
  - services/order-service.yaml
  - services/payment-service.yaml
  - services/settlement-service.yaml
  - services/support-service.yaml
  - services/wallet-service.yaml
  - configmaps/batch-service-configmap.yaml
  - configmaps/catalog-service-configmap.yaml
  - configmaps/common-configmap.yaml
  - configmaps/member-service-configmap.yaml
  - configmaps/order-service-configmap.yaml
  - configmaps/payment-service-configmap.yaml
  - configmaps/settlement-service-configmap.yaml
  - configmaps/support-service-configmap.yaml
  - configmaps/wallet-service-configmap.yaml
  - cronjobs/batch-service-cronjob-payment-outbox-cleanup.yaml
  - cronjobs/batch-service-cronjob-review-summary.yaml
  - cronjobs/batch-service-cronjob-subscription-order.yaml
  - /statefulset/database.yaml
  - /statefulset/elasticsearch.yaml
  - /statefulset/kafka.yaml
  - /statefulset/nginx.yaml
  - /statefulset/rabbitmq.yaml
  - /statefulset/redis.yaml
