apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apigateway.yaml
  - billing-service.yaml
  - catalog-service.yaml
  - config-repo-configmap.yaml
  - config.yaml
  - discovery.yaml
  - member-service.yaml
  - order-service.yaml
  - settlement-service.yaml
  - shop-service.yaml
  - subscription-service.yaml
