apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apigateway.yaml
  - batch-service.yaml
  - catalog-service.yaml
  - batch-service-configmap.yaml
  - catalog-service-configmap.yaml
  - common-configmap.yaml
  - discovery.yaml
  - member-service-configmap.yaml
  - member-service.yaml
  - order-service-configmap.yaml
  - order-service.yaml
  - payment-service-configmap.yaml
  - payment-service.yaml
  - settlement-service-configmap.yaml
  - settlement-service.yaml
  - support-service-configmap.yaml
  - support-service.yaml
  - wallet-service-configmap.yaml
  - wallet-service.yaml
  - /statefulset/database.yaml
  - /statefulset/elasticsearch.yaml
  - /statefulset/kafka.yaml
  - /statefulset/nginx.yaml
  - /statefulset/rabbitmq.yaml
  - /statefulset/redis.yaml
