apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-service
  labels:
    app: shop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-service
  template:
    metadata:
      labels:
        app: shop-service
    spec:
      containers:
        - name: shop-service
          image: node5dev/shop-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
  labels:
    app: shop-service
spec:
  type: ClusterIP
  selector:
    app: shop-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
