CREATE SCHEMA IF NOT EXISTS subscription;

CREATE TABLE subscription.subscription (
                                           id UUID NOT NULL,
                                           member_id UUID NOT NULL,

                                           product_id UUID NOT NULL,
                                           product_name VARCHAR(100),
                                           thumbnail_url VARCHAR,
                                           price_per_item BIGINT NOT NULL,
                                           quantity INTEGER NOT NULL DEFAULT 1,
                                           total_price BIGINT,

                                           subscription_status VARCHAR(20) NOT NULL,
                                           next_run_date DATE NOT NULL,
                                           delivery_address VARCHAR(100),

                                           created_at TIMESTAMP NOT NULL DEFAULT now(),
                                           modified_at TIMESTAMP NOT NULL DEFAULT now(),
                                           deleted_at TIMESTAMP,

                                           PRIMARY KEY (id)
);

CREATE INDEX idx_subscription_member_id ON subscription.subscription(member_id);
CREATE INDEX idx_subscription_product_id ON subscription.subscription(product_id);
CREATE INDEX idx_subscription_next_run_date ON subscription.subscription(next_run_date);

COMMENT ON TABLE subscription.subscription IS '구독 테이블';

COMMENT ON COLUMN subscription.subscription.id IS '구독 ID';
COMMENT ON COLUMN subscription.subscription.member_id IS '회원 ID';
COMMENT ON COLUMN subscription.subscription.product_id IS '상품 ID';
COMMENT ON COLUMN subscription.subscription.product_name IS '상품명';
COMMENT ON COLUMN subscription.subscription.thumbnail_url IS '상품 이미지 url';
COMMENT ON COLUMN subscription.subscription.price_per_item IS '단가';
COMMENT ON COLUMN subscription.subscription.quantity IS '수량';
COMMENT ON COLUMN subscription.subscription.total_price IS '총 금액';
COMMENT ON COLUMN subscription.subscription.subscription_status IS '구독 상태';
COMMENT ON COLUMN subscription.subscription.next_run_date IS '다음 결제일';
COMMENT ON COLUMN subscription.subscription.delivery_address IS '배송지';
COMMENT ON COLUMN subscription.subscription.created_at IS '생성일';
COMMENT ON COLUMN subscription.subscription.modified_at IS '수정일';
COMMENT ON COLUMN subscription.subscription.deleted_at IS '삭제일';


CREATE TABLE subscription.subscription_recurrence_rule (
                                                           id UUID NOT NULL,
                                                           subscription_id UUID NOT NULL,

                                                           recurrence_type VARCHAR(20) NOT NULL,
                                                           day_of_week INTEGER,
                                                           day_of_month INTEGER,

                                                           created_at TIMESTAMP NOT NULL DEFAULT now(),
                                                           modified_at TIMESTAMP NOT NULL DEFAULT now(),

                                                           PRIMARY KEY (id),

                                                           FOREIGN KEY (subscription_id) REFERENCES subscription.subscription(id)
);

CREATE INDEX idx_recurrence_subscription_id
    ON subscription.subscription_recurrence_rule(subscription_id);

-- Autogenerated: do not edit this file

CREATE TABLE subscription.BATCH_JOB_INSTANCE  (
                                                  JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
                                                  VERSION BIGINT ,
                                                  JOB_NAME VARCHAR(100) NOT NULL,
                                                  JOB_KEY VARCHAR(32) NOT NULL,
                                                  constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE subscription.BATCH_JOB_EXECUTION  (
                                                   JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
                                                   VERSION BIGINT  ,
                                                   JOB_INSTANCE_ID BIGINT NOT NULL,
                                                   CREATE_TIME TIMESTAMP NOT NULL,
                                                   START_TIME TIMESTAMP DEFAULT NULL ,
                                                   END_TIME TIMESTAMP DEFAULT NULL ,
                                                   STATUS VARCHAR(10) ,
                                                   EXIT_CODE VARCHAR(2500) ,
                                                   EXIT_MESSAGE VARCHAR(2500) ,
                                                   LAST_UPDATED TIMESTAMP,
                                                   constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
                                                       references subscription.BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE subscription.BATCH_JOB_EXECUTION_PARAMS  (
                                                          JOB_EXECUTION_ID BIGINT NOT NULL ,
                                                          PARAMETER_NAME VARCHAR(100) NOT NULL ,
                                                          PARAMETER_TYPE VARCHAR(100) NOT NULL ,
                                                          PARAMETER_VALUE VARCHAR(2500) ,
                                                          IDENTIFYING CHAR(1) NOT NULL ,
                                                          constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
                                                              references subscription.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE subscription.BATCH_STEP_EXECUTION  (
                                                    STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
                                                    VERSION BIGINT NOT NULL,
                                                    STEP_NAME VARCHAR(100) NOT NULL,
                                                    JOB_EXECUTION_ID BIGINT NOT NULL,
                                                    CREATE_TIME TIMESTAMP NOT NULL,
                                                    START_TIME TIMESTAMP DEFAULT NULL ,
                                                    END_TIME TIMESTAMP DEFAULT NULL ,
                                                    STATUS VARCHAR(10) ,
                                                    COMMIT_COUNT BIGINT ,
                                                    READ_COUNT BIGINT ,
                                                    FILTER_COUNT BIGINT ,
                                                    WRITE_COUNT BIGINT ,
                                                    READ_SKIP_COUNT BIGINT ,
                                                    WRITE_SKIP_COUNT BIGINT ,
                                                    PROCESS_SKIP_COUNT BIGINT ,
                                                    ROLLBACK_COUNT BIGINT ,
                                                    EXIT_CODE VARCHAR(2500) ,
                                                    EXIT_MESSAGE VARCHAR(2500) ,
                                                    LAST_UPDATED TIMESTAMP,
                                                    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
                                                        references subscription.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE subscription.BATCH_STEP_EXECUTION_CONTEXT  (
                                                            STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                                            SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                                            SERIALIZED_CONTEXT TEXT ,
                                                            constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
                                                                references subscription.BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE subscription.BATCH_JOB_EXECUTION_CONTEXT  (
                                                           JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                                           SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                                           SERIALIZED_CONTEXT TEXT ,
                                                           constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
                                                               references subscription.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE subscription.BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE subscription.BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE subscription.BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
