CREATE SCHEMA IF NOT EXISTS support;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE support."review_summary" (
	id uuid NOT NULL,
	product_id uuid NOT NULL,
    summary text NOT NULL,
    summary_end_date date NOT NULL,
	created_at timestamp NOT NULL,
	modified_at timestamp NOT NULL,
	CONSTRAINT pk_review_summary PRIMARY KEY (id),
    CONSTRAINT uk_review_summary_product_id UNIQUE (product_id)
);

CREATE TABLE support."review_static" (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    review_count int NOT NULL,
    rating_count_1 int NOT NULL,
    rating_count_2 int NOT NULL,
    rating_count_3 int NOT NULL,
    rating_count_4 int NOT NULL,
    rating_count_5 int NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT pk_review PRIMARY KEY (id),
    CONSTRAINT uk_review_product UNIQUE (product_id)
);

CREATE TABLE support."review_detail" (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    member_id uuid NOT NULL,
    nickname varchar(50) NOT NULL,
    order_id uuid NOT NULL,
    rating int NOT NULL,
    body text NULL,
    like_count int NOT NULL,
    embedding vector(1536),
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    deleted_at timestamp NULL,
    CONSTRAINT pk_review_detail PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_review_active_purchase
    ON support.review_detail (member_id, order_id, product_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_review_detail_embedding
    ON support.review_detail
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100)
    WHERE deleted_at IS NULL;

CREATE TABLE support."review_like_history" (
    id uuid NOT NULL,
    member_id uuid NOT NULL,
    review_id uuid NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT pk_review_like PRIMARY KEY (id),
    CONSTRAINT uk_review_like_member_review UNIQUE (member_id, review_id)
);

CREATE TABLE support."product_embedding" (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    content text NOT NULL,
    status varchar(20) NOT NULL,
    embedding vector(1536) NOT NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp NOT NULL,
    CONSTRAINT pk_product_embedding PRIMARY KEY (id),
    CONSTRAINT uk_product_embedding_product UNIQUE (product_id)
);

CREATE INDEX idx_product_embedding_embedding
    ON support."product_embedding"
    USING ivfflat (embedding vector_cosine_ops);

-- Autogenerated: do not edit this file

CREATE TABLE support.BATCH_JOB_INSTANCE  (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT ,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE support.BATCH_JOB_EXECUTION  (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT  ,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR(10) ,
	EXIT_CODE VARCHAR(2500) ,
	EXIT_MESSAGE VARCHAR(2500) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	    references support.BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE support.BATCH_JOB_EXECUTION_PARAMS  (
	JOB_EXECUTION_ID BIGINT NOT NULL ,
	PARAMETER_NAME VARCHAR(100) NOT NULL ,
	PARAMETER_TYPE VARCHAR(100) NOT NULL ,
	PARAMETER_VALUE VARCHAR(2500) ,
	IDENTIFYING CHAR(1) NOT NULL ,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	    references support.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE support.BATCH_STEP_EXECUTION  (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT NOT NULL,
	STEP_NAME VARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR(10) ,
	COMMIT_COUNT BIGINT ,
	READ_COUNT BIGINT ,
	FILTER_COUNT BIGINT ,
	WRITE_COUNT BIGINT ,
	READ_SKIP_COUNT BIGINT ,
	WRITE_SKIP_COUNT BIGINT ,
	PROCESS_SKIP_COUNT BIGINT ,
	ROLLBACK_COUNT BIGINT ,
	EXIT_CODE VARCHAR(2500) ,
	EXIT_MESSAGE VARCHAR(2500) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	    references support.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE support.BATCH_STEP_EXECUTION_CONTEXT  (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT ,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	    references support.BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE support.BATCH_JOB_EXECUTION_CONTEXT  (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT ,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	    references support.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE support.BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE support.BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE support.BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
