server:
  port: 8081 # random port

spring:
  application:
    name: billing-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: default       # 사용할 프로파일
  cloud:
    config:
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, prometheus

apigateway:
  host: http://localhost:8000