spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  datasource:
    url: jdbc:h2:mem:billing;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS billing
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: billing

api:
  v1: /api/v1

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY}
    success-url: ${TOSS_SUCCESS_URL}
    fail-url: ${TOSS_FAIL_URL}