spring:
  config:
    import: optional:configserver:http://localhost:8888

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4.1-nano
          max-completion-tokens: 512
          temperature: 1.0
      embedding:
        options:
          model: text-embedding-3-small
